INSERT INTO products (
    category_id,
    name,
    slug,
    sku,
    short_description,
    description,
    price,
    original_price,
    stock_quantity,
    thumbnail_url,
    rating_average,
    review_count,
    featured,
    hot,
    active
)
VALUES
    (
        (SELECT id FROM categories WHERE slug = 'laptop'),
        'MacBook Air M3 13 inch',
        'macbook-air-m3-13-inch',
        'LAP-MBA-M3-13',
        'MacBook Air M3 mỏng nhẹ, phù hợp học tập và làm việc.',
        'MacBook Air M3 sở hữu thiết kế mỏng nhẹ, hiệu năng mạnh và thời lượng pin dài.',
        27990000,
        29990000,
        10,
        'https://placehold.co/600x400?text=MacBook+Air+M3',
        4.8,
        12,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        (SELECT id FROM categories WHERE slug = 'laptop'),
        'ASUS TUF Gaming A15',
        'asus-tuf-gaming-a15',
        'LAP-ASUS-TUF-A15',
        'Laptop gaming hiệu năng cao.',
        'ASUS TUF Gaming A15 phù hợp chơi game, thiết kế đồ họa và lập trình.',
        22990000,
        24990000,
        8,
        'https://placehold.co/600x400?text=ASUS+TUF+A15',
        4.6,
        8,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        (SELECT id FROM categories WHERE slug = 'dien-thoai'),
        'iPhone 16 128GB',
        'iphone-16-128gb',
        'PHONE-IP16-128',
        'iPhone 16 phiên bản bộ nhớ 128GB.',
        'iPhone 16 có hiệu năng mạnh, camera chất lượng cao và thiết kế hiện đại.',
        21990000,
        22990000,
        15,
        'https://placehold.co/600x400?text=iPhone+16',
        4.9,
        20,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        (SELECT id FROM categories WHERE slug = 'dien-thoai'),
        'Samsung Galaxy S25',
        'samsung-galaxy-s25',
        'PHONE-SS-S25',
        'Điện thoại Samsung Galaxy S25.',
        'Samsung Galaxy S25 sở hữu màn hình sắc nét và nhiều tính năng thông minh.',
        19990000,
        21990000,
        12,
        'https://placehold.co/600x400?text=Galaxy+S25',
        4.7,
        15,
        TRUE,
        FALSE,
        TRUE
    ),
    (
        (SELECT id FROM categories WHERE slug = 'tai-nghe'),
        'Apple AirPods 3rd Generation',
        'apple-airpods-3rd-generation',
        'HEADPHONE-AIRPODS-3',
        'Tai nghe không dây AirPods thế hệ thứ ba.',
        'AirPods 3 mang đến âm thanh sống động và khả năng kết nối thuận tiện.',
        3990000,
        4490000,
        35,
        'https://placehold.co/600x400?text=AirPods+3',
        4.5,
        5,
        TRUE,
        TRUE,
        TRUE
    ),
    (
        (SELECT id FROM categories WHERE slug = 'tai-nghe'),
        'Apple AirPods Max',
        'apple-airpods-max',
        'HEADPHONE-AIRPODS-MAX',
        'Tai nghe chụp tai cao cấp của Apple.',
        'AirPods Max có thiết kế cao cấp, chống ồn chủ động và âm thanh chất lượng cao.',
        12990000,
        13990000,
        14,
        'https://placehold.co/600x400?text=AirPods+Max',
        4.7,
        9,
        FALSE,
        TRUE,
        TRUE
    ),
    (
        (SELECT id FROM categories WHERE slug = 'may-anh'),
        'Canon EOS 250D',
        'canon-eos-250d',
        'CAMERA-CANON-250D',
        'Máy ảnh DSLR nhỏ gọn dành cho người mới.',
        'Canon EOS 250D phù hợp chụp ảnh, quay video và sáng tạo nội dung.',
        15990000,
        16990000,
        6,
        'https://placehold.co/600x400?text=Canon+EOS+250D',
        4.6,
        7,
        TRUE,
        FALSE,
        TRUE
    ),
    (
        (SELECT id FROM categories WHERE slug = 'phu-kien'),
        'Chuột Logitech MX Master 3S',
        'chuot-logitech-mx-master-3s',
        'ACC-LOGI-MX3S',
        'Chuột không dây dành cho công việc.',
        'Logitech MX Master 3S có thiết kế công thái học và khả năng kết nối đa thiết bị.',
        1890000,
        2290000,
        20,
        'https://placehold.co/600x400?text=MX+Master+3S',
        4.8,
        18,
        FALSE,
        TRUE,
        TRUE
    );